spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# User Service
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/**

# Skill Service
spring.cloud.gateway.server.webmvc.routes[1].id=skill-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://skill-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/skills/**

# Learning Service
spring.cloud.gateway.server.webmvc.routes[2].id=learning-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://learning-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/learning-requests/**

# Match Service
spring.cloud.gateway.server.webmvc.routes[3].id=match-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://match-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/matches/**

# Feedback Service
spring.cloud.gateway.server.webmvc.routes[4].id=feedback-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://feedback-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/feedback/**
# Actuator
management.endpoints.web.exposure.include=health,info

# JWT Settings
jwt.secret=learnloop-super-secret-key-for-jwt-authentication-2026
jwt.expiration=86400000


